### ISSUE TITLE
Compatibility with Sublime Text build 3114?

### ISSUE THREAD

**Issue by danielbachhuber** [wesbos/cobalt2#102]
Since updating to Sublime Text build 3114, I've noticed some coloring issues:

Build 3114:

![image](https://cloud.githubusercontent.com/assets/36432/15320204/1f362142-1be4-11e6-9531-f22433a0b80c.png)

![image](https://cloud.githubusercontent.com/assets/36432/15320207/24b38632-1be4-11e6-88a1-cb8198576e04.png)

Build 3013:

![image](https://cloud.githubusercontent.com/assets/36432/15320279/7ee44326-1be4-11e6-8775-5f8e0153b99f.png)

![image](https://cloud.githubusercontent.com/assets/36432/15320286/874edc1a-1be4-11e6-98d7-4d5f82f4fe33.png)

Is this something that's expected to be fixed in Cobalt?

**Comment by wesbos** [comment]
Looks like there were a few regressions in the syntax highlighting for Sublime as there was a big update - you are best to report this on the Sublime github. Looks like there are a few open issues over PHP:

https://github.com/sublimehq/Packages/issues/389

**Comment by danielbachhuber** [comment]
Ok, I'll follow along on that issue.
