### ISSUE TITLE
Latest update drains sidebar colours on OS X

### ISSUE THREAD

**Issue by asomorjai** [wesbos/cobalt2#105]
<img width="742" alt="screen shot 2016-05-30 at 11 19 46" src="https://cloud.githubusercontent.com/assets/4947187/15645409/84c8626c-2658-11e6-902f-033e7a8c7d8c.png">

**Comment by kyhwsk** [comment]
I'm experiencing the same problem.

**Comment by asomorjai** [comment]
That's strange, but I found the solution: open you User Preferences, then look for this line which sneaked back during the last Cobalt2 or Sublime update:
	"theme": "Default.sublime-theme",

Modify this to point to the Cobalt2 theme:
	"theme": "Cobalt2.sublime-theme",

and everything is back to normal.

**Comment by wesbos** [comment]
Yeah sometimes Sublime does tha when updating a sidebar theme - apparently it will be fixed in a few updates. Enjoy!
