### ISSUE TITLE
Syntax weirdness in css media queries

### ISSUE THREAD

**Issue by luclemo** [wesbos/cobalt2#106]
Heya, just noticed that the first selector inside a css (not sass or stylus) media query shows up as white. Not sure if it's a bug or  ¯\_(ツ)_/¯

![screen shot 2016-05-31 at 8 28 21 pm](https://cloud.githubusercontent.com/assets/1451515/15694734/4fe44e3c-276e-11e6-93ee-78fd91e63079.png)

**Comment by wesbos** [comment]
Which version of Sublime Text (build number from "About sublime text)) are you using?

**Comment by luclemo** [comment]
Ah yeah, build 3114

**Comment by wesbos** [comment]
closing this - I don't think it's an issue with Cobalt but rather the CSS highlighter. Feel free to reopen if you think otherwise
