### ISSUE TITLE
ES6 classes and object keys colors not working

### ISSUE THREAD

**Issue by rosston** [wesbos/cobalt2#107]
In trying to test https://github.com/wesbos/cobalt2-atom/pull/7, I discovered that https://github.com/wesbos/cobalt2/commit/157292725a6717807fd3372bdc7a7e00bb213be6 doesn't seem to be working, at least with my config. The screenshot at https://github.com/wesbos/cobalt2/issues/103#issuecomment-222156751 looks much different than mine:

<img width="313" alt="screen shot 2016-05-31 at 23 23 42" src="https://cloud.githubusercontent.com/assets/108518/15697307/ebf2692c-2786-11e6-8cf4-3496287ea1c4.png">

I'm on Sublime Text 3, Stable Channel, Build 3114 (May 12, 2016) and using the default JavaScript language definition.

**Comment by gonzamvita** [comment]
You must test JavaScript Next definition. It was the same for me, but with that definition now its ok.
Obviously if it should work without that I'll be happy to know.

**Comment by rosston** [comment]
Actually, it looks not updated for me using both the JavaScript Next and Babel definitions.

JavaScript Next
<img width="316" alt="js-next" src="https://cloud.githubusercontent.com/assets/108518/15768476/37e5f242-291f-11e6-830f-0dd8f3020c6f.png">

Babel
<img width="313" alt="babel" src="https://cloud.githubusercontent.com/assets/108518/15768479/3caae51c-291f-11e6-8b14-e912f84be554.png">

I imagine #108 will probably fix it. Or maybe I've screwed up my environment somehow. I'll wait until that merges before actually worrying about it.

**Comment by rosston** [comment]
Derp, it not working with JavaScript Next and Babel definitions was totally my fault. I'd messed up my config using SublimeLinter somehow (probably my own fault).

So, this issue is _only_ about making the changes work with the default JavaScript definition, which #108 mostly fixes.

**Comment by rosston** [comment]
This is fixed by #108.
