### ISSUE TITLE
Sidebar selected item highlight

### ISSUE THREAD

**Issue by anirudh-modi** [wesbos/cobalt2#110]
![screen shot 2016-06-04 at 11 48 26 pm](https://cloud.githubusercontent.com/assets/16587779/15801323/fbb0b460-2aae-11e6-961f-dc0d9bc6b6a5.png)

Is there any way to increase the width of the yellow marker in sidebar for selected file?

**Comment by wesbos** [comment]
There is no setting, no. It's just a PNG in the folder that you _could_ edit.

**Comment by anirudh-modi** [comment]
Ok. thanks for the response.
