### ISSUE TITLE
Keywords BG color

### ISSUE THREAD

**Issue by preskaper** [wesbos/cobalt2#111]
is there any way to remove background color from keywords?

![Alt](http://image.prntscr.com/image/1e33b732a5e9401f8dcc11d66ec9522a.png)

thanx

**Comment by konstantinpschera** [comment]
Yeah would be cool. That's the reason I am not using Cobalt2!

**Comment by wesbos** [comment]
Sublime themes don't have the option for settings, so unfortunately not at the moment

**Comment by evandavis** [comment]
@konstantinpschera @preskaper https://github.com/evandavis/cobalt2/commit/d7a61a70bd0ea16d6adc86b97d0c2e0924aabc7f You can remove the background colors manually.

**Comment by wesbos** [comment]
:) You're welcome!
