### ISSUE TITLE
Popup styling

### ISSUE THREAD

**Issue by buildersbrewery** [wesbos/cobalt2#113]
https://www.sublimetext.com/3dev

> Build 3116
> - Color Schemes: Added popupCss key, for defining default popup style sheets.

**Comment by wesbos** [comment]
Oh wow this is great! Looks like the default theme ships with some styling - I'll have to look at how to port + change that to Cobalt2

**Comment by codeangler** [comment]
I don't want to duplicate issues so I 'll start with a comment.   I believe what @buildersbrewery  is referring to popupCss also may apply to tooltips that mdpopups is using.

"Mdpopups will use your color scheme to create popups/phantoms that fit your editors look."

**Comment by buildersbrewery** [comment]
@wesbos @codeangler functionality was added in wesbos/cobalt2@30e154b in PR #126 which closed #125
