### ISSUE TITLE
Make HTML class italic too

### ISSUE THREAD

**Issue by wesbos** [wesbos/cobalt2#114]
Not sure why, but the class attribute in HTML isn't italic. This needs investigating. I'll look soon unless someone else wants to hunt it down 

![](http://wes.io/gZWM/content)/

**Comment by fredpbarker** [comment]
I was able to fix this. This is my first time using GitHub, so issues, pull requests, etc. are all new to me. Forgive me if I'm not doing it right! I submitted the pull request a moment ago.

Before:

![image](https://cloud.githubusercontent.com/assets/15805865/17763062/e491fcfc-64ca-11e6-93fd-1e1e02b0da97.png)

After

![after](https://cloud.githubusercontent.com/assets/15805865/17763216/01572974-64cc-11e6-895a-7daca39858e4.png)

**Comment by wesbos** [comment]
Perrrfect - thanks a ton for this :) 

Going to cut a release now
