### ISSUE TITLE
bracket matcher doesnt show on focussed line

### ISSUE THREAD

**Issue by jonsrose** [wesbos/cobalt2#115]
When I go to a line in the text editor and move the cursor to a  bracket, the bracket does not get the bracket matcher styling (bottom border turns yellow) even though I do see the styling on the matching bracket. It appears that the background for the active editor line is in front of the bottom border. 

I think this can be fixed by setting a z-index=0 on the bracket matcher css.

**Comment by rosston** [comment]
This repository is for the Sublime Text theme. It sounds like the issue you're talking about is in the [Atom theme](https://github.com/wesbos/cobalt2-atom), given that I can reproduce it there but not in Sublime. Is that right?

**Comment by jonsrose** [comment]
That is correct, I was seeing the issue in Atom theme.

**Comment by rosston** [comment]
@jonsrose or @wesbos: Feel free to close this issue. I created an issue for the Atom theme: https://github.com/wesbos/cobalt2-atom/issues/9
