### ISSUE TITLE
Is there a setting for increasing the font size of the status bar?

### ISSUE THREAD

**Issue by AlexVPopov** [wesbos/cobalt2#117]
I am using ST3. I installed the RuboCop package, which shows code style offences in the status bar when saving a Ruby file. Is there a way to increase the font size of the status bar, as currently, it is too small to read it comfortably?

**Comment by wesbos** [comment]
Unfortunately not - not sure if it's possible to have this as a setting or not. If someone is willing to take a look that would be great.
