### ISSUE TITLE
Color for "Definitions" text is difficult to read

### ISSUE THREAD

**Issue by jwalton512** [wesbos/cobalt2#125]
As shown below, the content in the `Definitions` modal is difficult to read.

![image](https://cloud.githubusercontent.com/assets/1199655/18648153/36491028-7e6e-11e6-8d36-f643b02e2f5a.png)

**Comment by wesbos** [comment]
Thanks a ton. Anyone want to tackle this one?

**Comment by jwalton512** [comment]
@wesbos -- is there by chance any type of guide you are aware of that outlines the theme configurations in Sublime?  I tried to search around for one, but didn't find anything

**Comment by jwalton512** [comment]
@wesbos tracked down some info, should be able to submit a pull request soon.

**Comment by wesbos** [comment]
yay :) 

It's really new to Sublime so I haven't dipped my toes into this that much
