### ISSUE TITLE
Status bar font size as a parameter

### ISSUE THREAD

**Issue by nMustaki** [wesbos/cobalt2#129]
Hello,

thanks you very much for Cobalt2, I really love it !
I have one minor nitpic about the status font bar which is too small for me; I have changed it manually but I may not be the only one : would you accept a pull request which adds a setting controlling the font (as it is already done with sidebar_font_big" for instance) ?

Thanks again,
Nathan

**Comment by wesbos** [comment]
Yes I'd love a PR to add in this option!

**Comment by nMustaki** [comment]
Here it is : https://github.com/wesbos/cobalt2/pull/131
