### ISSUE TITLE
How to use this theme on VS code 

### ISSUE THREAD

**Issue by SirwanAfifi** [wesbos/cobalt2#143]
It's really great theme @wesbos 👍 👍  well-done

I wonder if there's a way to import (using) this theme on vs code, I just installed the version you have published for VS code on marketplace but seems that it doesn't compatible with latest version of VS code?

**Comment by louisotto** [comment]
To use it, install by hitting Ctrl + P/Cmd + P and pasting 

Then reload, you should see your fonts change colour, but now go to File -> Preferences -> Settings and in the user panel add this: "workbench.colorTheme": "Cobalt2"

You should now see it in all its glorious form :)

**Comment by wesbos** [comment]
This theme is in the VS code marketplace so use that and you'll get updates
