### ISSUE TITLE
Light sidebar

### ISSUE THREAD

**Issue by KSVQ** [wesbos/cobalt2#145]
no matter what I do my left sidebar is always light. How can I get it to be dark?

**Comment by wesbos** [comment]
Did you use the settings in the Readme?

**Comment by wesbos** [comment]
Specifically these two:

```
"color_scheme": "Packages/Theme - Cobalt2/cobalt2.tmTheme",
"theme": "Cobalt2.sublime-theme", 
```

**Comment by KSVQ** [comment]
It turned out that I had one file overriding information from another file. I got it to work. Thanks!

**Comment by wesbos** [comment]
👌
