### ISSUE TITLE
Sublime Dev support

### ISSUE THREAD

**Issue by humiaozuzu** [wesbos/cobalt2#146]
The theme seems not working as expected on ST3 dev
https://www.sublimetext.com/3dev

**Comment by rosston** [comment]
Is it the tabs that are messed up? That's a known issue: https://twitter.com/wesbos/status/852591041266024448

**Comment by wesbos** [comment]
Yeah the tabs should be fixed in the next release - already reported to the dev team

**Comment by rpkoller** [comment]
The Tab is working again in the latest release now: 

![bildschirmfoto 2017-04-22 um 08 37 38](https://cloud.githubusercontent.com/assets/1665422/25302111/132ce58e-2737-11e7-8865-b52bc88671f8.png)

but i am curious if it would be possible and an reasonable idea to get the window title bar to the blackish state the adaptive theme has? got used to the new look while the tabs weren't working for cobalt2. ;)
 
![bildschirmfoto 2017-04-22 um 08 37 07](https://cloud.githubusercontent.com/assets/1665422/25302127/5669725e-2737-11e7-983f-c6ce1f4d64b3.png)

**Comment by humiaozuzu** [comment]
+1 for the blackish state, so beautiful!
