### ISSUE TITLE
custom style the vscode cursor no longer works in newest vs code Version 1.18.0 

### ISSUE THREAD

**Issue by fortrustit** [wesbos/cobalt2#157]
vscode-custom-css extension no longer works for code version 1.18.0.

**Comment by wesbos** [comment]
Oh this is for the VS Code theme - please open an issue over there

**Comment by rosston** [comment]
Link for the VS Code theme since it's not referenced in this repo (that I can see): https://github.com/wesbos/cobalt2-vscode

**Comment by wesbos** [comment]
thanks!
