### ISSUE TITLE
White space color changed after updating to Sublime 3.1

### ISSUE THREAD

**Issue by scarhand** [wesbos/cobalt2#163]
With `"draw_white_space": "selection"` white space used to look like this:
![image](https://camo.githubusercontent.com/033f1b7d6b5ea9568ac2db9924de612ef1d77008/687474703a2f2f7765732e696f2f5949686f2f636f6e74656e74)

I loved the unobtrusive way of showing 'invisibles', I even changed the draw_white_space setting to `all` :)

However, since Sublime 3.1 it looks like this:
![image](https://user-images.githubusercontent.com/34021/40040894-5bb4c0f8-581c-11e8-8431-e4484686ee78.png)

The white space color is much more in your face in this color scheme. I would very much love to have the old coloring back.

**Comment by narikazu** [comment]
@rosston 

Yes, #162 definitely has fixed it. Please find the attached image. 

![screen shot 2018-05-17 at 09 13 38](https://user-images.githubusercontent.com/827596/40161969-a91eb60e-59b2-11e8-8c71-b568cb601d10.png)

It would be fantastic if you could merge it into the master. :)

**Comment by scarhand** [comment]
Sorry, I totally missed the PR when I created this issue.
But yeah, it does definitely fix it!

**Comment by rosston** [comment]
@narikazu I'm a "Contributor", not a "Collaborator", so I can't merge it, sorry!

**Comment by wesbos** [comment]
I'm not using Sublime any more so is there someone who would like to help maintain this?

**Comment by wesbos** [comment]
I merged this and released a new version - enjoy!
