### ISSUE TITLE
Plans to rewrite in sublime-color-scheme format?

### ISSUE THREAD

**Issue by john-cj** [wesbos/cobalt2#165]
[`tmTheme` is a legacy format](https://www.sublimetext.com/docs/3/color_schemes_tmtheme.html). Are there any plans to rewrite it as `sublime-color-scheme`?

**Comment by wesbos** [comment]
I'm not using Sublime at the moment so it's unlikely 

Is there anyone who would like to step up and maintain this?

**Comment by john-cj** [comment]
@wesbos Just out of curiosity, what editor/IDE you use currently?
