### ISSUE TITLE
Tab Scrolling Feature Issue

### ISSUE THREAD

**Issue by bengold** [wesbos/cobalt2#37]
When the new `enable_tab_scrolling` feature is set to true, it looks like this:

![Screenshot](http://f.cl.ly/items/3p2n3v3S1J3m1k3w0m1w/RpTBtSoqe9QkA377ALG2yYm1rMswYc7Ysijxg4KhsDc.png)

Those arrows don't have enough padding, and it looks kind of bad.

**Comment by wesbos** [comment]
This should be fixed. LMK if you have any more issues.
