### ISSUE TITLE
File name shifts if I change content

### ISSUE THREAD

**Issue by gornostal** [wesbos/cobalt2#42]
First I must say wow what a gorgeous theme!

I just started using it and noticed one thing that kind of breaks a great UX.
It's file name that shifts inside a tab button when document gets "dirty".

![screencast 2014-11-25 11-51-58](https://cloud.githubusercontent.com/assets/1202543/5180992/ac24085a-749a-11e4-8eb1-b3462a3ae180.gif)
(sorry for bad quality)

Reproducible in ST3 in Ubuntu 14.04.

**Comment by gornostal** [comment]
@wesbos are you planning to release a new version that includes fixes since November?

**Comment by wesbos** [comment]
Ah yes, so sorry I'll do that very soon.

**Comment by gornostal** [comment]
Thank you.
