### ISSUE TITLE
Increasing font.size for the Tab bar clips the tab text

### ISSUE THREAD

**Issue by gribelu** [wesbos/cobalt2#43]
Hello,

I'm trying to increase the font size of the tab bar because my eyes aren't so great and the display has high DPI so 11px just isn't enough.

I succeeded, but now the text is clipped at the bottom. I tried fiddling with the height and margins but the clipping is unchanged. Thoughts?

Cheers,
Bogdan
![screenshot26](https://cloud.githubusercontent.com/assets/40509/5333890/ad20644e-7e8e-11e4-82f9-32a215e9fdf8.png)
![screenshot26](https://cloud.githubusercontent.com/assets/40509/5333910/e8645bb4-7e8e-11e4-8461-a2b7ad708a69.png)

**Comment by wesbos** [comment]
This is a shortfall of Sublime Text themes - not possible unfortunately.
