### ISSUE TITLE
Conflicts with Color Highlighter plugin?

### ISSUE THREAD

**Issue by wavded** [wesbos/cobalt2#49]
First off, thanks for the great theme, I dig.

Secondly, I noticed the cobalt2 color scheme provides the result below when using the popular [Color Highlighter](https://github.com/Monnoroch/ColorHighlighter) plugin.  Essentially these white-filled areas should be colored:

![screen shot 2014-12-27 at 12 10 13 am](https://cloud.githubusercontent.com/assets/26638/5560590/c10cceca-8d5c-11e4-9e81-b5cd80cdd0c5.png)

I reported it here because when I switch to any of the default color schemes, the correct colors show up.  Any ideas?

**Comment by WilliamYoung** [comment]
I also have this issue. color highlighter cannot work with Cobalt2.
