### ISSUE TITLE
Python error text fuzzy

### ISSUE THREAD

**Issue by CrystalDave** [wesbos/cobalt2#50]
I'm running into an issue where specifically the Red on blue color combination which designates Error in Python has what looks like aliasing issues. (On Ubuntu, if it matters) Everything else comes out crisp and clear, and this exists outside of flipping 'subpixel_antialias' in the font options.

I'm not certain that it's an issue with the theme, but I've ruled out most of the obvious options and figured I'd raise it here in case there's something I've missed.

Image attached for illustration, font size blown up to make it clearer
![cobalt_fuzzy](https://cloud.githubusercontent.com/assets/1232245/5622084/2565e7de-94f2-11e4-9c40-da261bcc251b.PNG)

**Comment by alexwidener** [comment]
Preferences.sublime-settings: (Settings > User)

"font_options": ["no_antialias"]

**Comment by wesbos** [comment]
Thanks @alexwidener
