### ISSUE TITLE
Font in the sidebar is strange

### ISSUE THREAD

**Issue by zjhui** [wesbos/cobalt2#51]
![image](https://cloud.githubusercontent.com/assets/1116346/5658148/a610706a-9737-11e4-8d55-0dded4413059.png)
Hi, I use windows 7 64bit. When i installed this theme, the font on the sidebar looks so strange. Did i miss some fonts?

**Comment by WilliamYoung** [comment]
try restart Sublime

**Comment by davguij** [comment]
It happened to me too, on ST2 Win7 64bit.
Here's what I did to fix it:
1. Open package control tools → Command Palette and type List
2. Select "Package Control: List Package"
3. Type "Cobalt2" and select "Theme - Cobalt2"
4. Open "Cobalt2.sublime-theme".
5. Go to lines 483-492 and look for this block:
    // Sidebar heading
    {
        "class": "sidebar_heading",
        "color": [210, 210, 210],
        "font.bold": true,
        "shadow_color": [0, 0, 0],
        "shadow_offset": [0, -1]
    },
    // Sidebar entry
    {
        "class": "sidebar_label",
        "color": [125, 125, 125],
        "shadow_color": [0, 0, 0],
        "shadow_offset": [0, -1],
        "font.size": 12
    },
6. Delete the shadow_color and shadow_offset lines.
7. Done!
You can also fork the repo so your changes don't get lost when the theme is updated.
