### ISSUE TITLE
Cobalt2 not work well with Ruby do block.

### ISSUE THREAD

**Issue by WilliamYoung** [wesbos/cobalt2#52]
This is a sample from Rails 2.3.2 ..\lib\active_support\memoizable.rb
![image](https://cloud.githubusercontent.com/assets/4438316/5915478/3421c530-a641-11e4-9f27-731f5c2af2d8.png)

**Comment by wesbos** [comment]
This is an issue with your syntax highlighter - the theme doesn't really handle too much language specific stuff.
