### ISSUE TITLE
SCSS syntax highlight not working properly with theme

### ISSUE THREAD

**Issue by vdecree** [wesbos/cobalt2#55]
Hi there,

I've just installed this lovely theme and it's by far my favorite of all I've tried, however the SCSS syntax package doesn't seem to work well since using the theme. I have to re-select the SCSS from the language dropdown for highlighting to take effect, despite it being selected by default. Is this a known issue?

**Comment by wesbos** [comment]
Not an issue with the theme but rather how Sublime or another package (like colour highlighter) is handling it.


One thing you can try is:


![](http://wes.io/a9Dt/content)

**Comment by vdecree** [comment]
Hi Wes,

I did try this as my initial thoughts were the same. However this didn't seem to help. I've since reset my ST3 to a fresh install and reinstalled my packages, including Cobalt and this time around it seems to be OK. Strange but at least it's working now - didn't want to use another theme!

**Comment by wesbos** [comment]
Right on - glad you got it working!
