### ISSUE TITLE
Error with theme, attempt to install package fails

### ISSUE THREAD

**Issue by mauphie** [wesbos/cobalt2#57]
I'm running Sublime3 Build 3083. All of a sudden, the Cobalt theme stopped working. I attempted to re-install the package, but can't find it the package manager. 

Obviously a reinstall is in order, but why can't i find it in Package manager? 

FWIW the Error message comes up as 
> Error loading colour scheme Packages/User/Color Highlighter/themes/cobalt2 (SL).tmTheme: 
> Error parsing plist xml: expected element name in file Packages/User/Color Highlighter/themes/cobalt2 > (SL).tmTheme on line: 479

Took a look in User Preferences and it reads:
> "color_scheme": "Packages/User/SublimeLinter/cobalt2 (SL).tmTheme"

Thanks for the help!

**Comment by wesbos** [comment]
Hrm - can you try disable sublime linter and re-endable the real theme? 

Sublime Linter copies over the theme and adds in new definitions.

**Comment by ssteinerx** [comment]
Unfortunately, it's almost impossible to get Sublime Linter the heck out of there.  All "cobalt2" theme choices from within Preferences set this:
```
	"color_scheme": "Packages/User/SublimeLinter/cobalt2 (SL).tmTheme",
```
even after sublime linter (which I rely on!) is removed.

Since this repo does not show in Package Manager, I git cloned it to:
```
(~/Library/Application Support/Sublime Text 3/Packages$)
```
Is that where it should go?  I haven't manually installed anything in so long, I forget!

Thanks,

Steve
BTW, just bought your book/video package.  Great stuff!

**Comment by wesbos** [comment]
This repo should be in Package Manager - I know they were having issues - try again?

Sublime Linter is a huge pain - I rely on it too, but it really messes with themes - hoping this changes with future versions of Sublime Text.

Glad you got the book! Enjoy!

**Comment by ssteinerx** [comment]
Package Control itself is working fine, Cobalt2 is not accessible therefrom.

**Comment by wesbos** [comment]
Still having issues?

**Comment by mauphie** [comment]
It is back working, although honestly I can't remember how it was resolved.

**Comment by wesbos** [comment]
Thanks!

**Comment by raptox** [comment]
I can't find it in package manager :(

**Comment by wesbos** [comment]
Do you have it installed already? Look under listed packages

**Comment by raptox** [comment]
yes, my bad, it was already installed, thanks for the quick answer!
