### ISSUE TITLE
React JS

### ISSUE THREAD

**Issue by adibhanna** [wesbos/cobalt2#60]
Hello, i'm having issues when using React JS. basically, when i write jsx (html tags), it's adding blue lines next to each tag. (i'm writing my js inside html)

**Comment by wesbos** [comment]
Do you have a JSX syntax highlighter installed? Typically the theme doesn't address language specific things like this.

**Comment by wesbos** [comment]
I use JSX to write Rract all day long and I have no issues with the Babel syntax highlighter
