### ISSUE TITLE
No visual indication which pane is active and in focus

### ISSUE THREAD

**Issue by rpkoller** [wesbos/cobalt2#68]
Hi Wes. At first thanks for the great theme and color scheme. There is only one slight flaw - but i am unsure if it would be possible to fix at all. At the moment you are unable to figure out which of the panes is actually active and in focus. 

The only indication is the indent guide if the draw active option is set - but only in case you have the cursor inside a function. 
![screenshot](https://cloud.githubusercontent.com/assets/1665422/9005696/b456273e-3780-11e5-8c8a-8d906a7d032b.png)

aside that both panes look identical in the screenshot. both highlight the active tab with a orange underline as well as highlight the line the cursor is in. so basically no way visually to distinguish which is the active pane. would it perhaps be possible to distinguish between an active window and a non active by the background color. use the current coloring for the active one and for all others a lighter background color? best regards Ralf

**Comment by wesbos** [comment]
I don't know if this is possible..
