### ISSUE TITLE
Adjust spacing of tab bar arrow icons

### ISSUE THREAD

**Issue by danielandrews** [wesbos/cobalt2#77]
Nitpicky issue but the spacing of the arrow icons could use more consistent spacing so that they aren't up against the edges of the screen. If the 'prev/next' icons could be centered within their allotted space & the select dropdown could have appropriate padding on the right that'd be ideal.

https://www.dropbox.com/s/samld4kd4doiks4/Screenshot%202015-08-27%2010.37.02.png?dl=0

**Comment by wesbos** [comment]
Ah yes! I don't use the arrows so I've never noticed this. 

Any chance you want to dig into the theme and fix it?

**Comment by danielandrews** [comment]
Sure thing. Line 13 of Cobalt2.sublime-theme:
```
"content_margin": [2, 0, 4, 3],
```
Gets the following effect:

![screenshot 2015-08-27 11 55 49](https://cloud.githubusercontent.com/assets/791336/9525552/a19b8b56-4cb2-11e5-9154-c069f3b44858.png)


Glad to submit a pull req if you prefer.

**Comment by wesbos** [comment]
that would be great!

**Comment by wesbos** [comment]
This was fixed in another PR
