### ISSUE TITLE
Theme broken since 2.0.3

### ISSUE THREAD

**Issue by floriandotorg** [wesbos/cobalt2#80]
Hi,

after the last update my sublime looks like this:

![bildschirmfoto 2015-09-21 um 08 10 48](https://cloud.githubusercontent.com/assets/6143734/9986251/a3ccb012-603a-11e5-8047-87d5a1c02be3.png)

**Comment by wesbos** [comment]
Looks like it just got deactivated. 

Open your settings and put this in there:

```js
"theme": "Cobalt2.sublime-theme",
```

**Comment by floriandotorg** [comment]
That was way to obvious, thanks :-P
