### ISSUE TITLE
Tab racognisable when in "transient" state (or preview)

### ISSUE THREAD

**Issue by caesarsol** [wesbos/cobalt2#81]
In the [Sublime Material Theme](https://github.com/equinusocio/material-theme/) when a tab is only **transient** its recognisable (the name is in italic font), only when you voluntarily open it becomes a normal tab.

From https://www.sublimetext.com/docs/3/api_reference.html:
> sublime.TRANSIENT: Open the file as a preview only: it won't have a tab assigned it until modified

I guess it is introduced in these lines: 
https://github.com/equinusocio/material-theme/blob/master/Material-Theme-Darker.sublime-theme#L349

Would it be possible to reproduce here?
I could try to submit a PR if i find the time.

**Comment by wesbos** [comment]
That would be pretty cool - I'd love a PR for this!

**Comment by wesbos** [comment]
Oops - tried to assign you but I can't

**Comment by caesarsol** [comment]
I'll try tomorrow!
