### ISSUE TITLE
Highlighted Line is not working

### ISSUE THREAD

**Issue by sundarv85** [wesbos/cobalt2#84]
The highlighted line as described [here](https://github.com/wesbos/cobalt2#highlighted-line) is not working.

[This is what I see](http://cl.ly/image/1g3H1e2R1f21)

Here line no 60 is highlighted, which we can see with the number being highlighted. I’m using Sublime build 3083.

**Comment by wesbos** [comment]
Hey! Use `"highlight_line": true,` in your Sublime Text settings to turn this on. :smile:

**Comment by sundarv85** [comment]
duh!!.. You are correct.. This solves it. Sorry about it @wesbos
