### ISSUE TITLE
Can cobalt2 support WebStorm?

### ISSUE THREAD

**Issue by Hongbo-Miao** [wesbos/cobalt2#85]
I know this place is for Sublime, but I don't know any place I can request... I really like cobalt2. Anyway we can use cobalt2 in WebStorm? Thanks!

**Comment by wesbos** [comment]
Do themes for Intellij work for webstorm? 

@TheSerenin is working on one - 

https://twitter.com/TheSerenin/status/663468247732350976

**Comment by TheSerenin** [comment]
I'm going on an assumption here and say yes.

Despite my port not being done you can try it and give feedback in case it doesn't :)

**Comment by Hongbo-Miao** [comment]
Cool, I would like to try!

**Comment by TheSerenin** [comment]
https://github.com/TheSerenin/cobalt2-intellij




Just download the cobalt2.icls and put it in your webstorm folder. 





Try a Google search on how to in case your don't know how to install it. :)

**Comment by Hongbo-Miao** [comment]
Thanks!!

**Comment by Hongbo-Miao** [comment]
This is for other people who want to use cobalt2:

Install location for OSX. Copy cobalt2.icls to this place depends on which app you are using:
/Users/YourUserName/Library/Preferences/WebStorm11/colors
/Users/YourUserName/Library/Preferences/IntelliJIdea15/colors

App Setting
Preferences -> Editor -> Colors & Fonts -> Scheme -> Cobalt2

**Comment by wesbos** [comment]
Thank you!

**Comment by droid-Q** [comment]
@Hongbo-Miao  it is not working .i am using IDEA 15.0.3.

**Comment by Hongbo-Miao** [comment]
@droid-Q feels like cobalt2-intellij is not really under official maintenance, so I already changed to use default style in WebStorm

**Comment by ngehlert** [comment]
@AlmogRnD you can try out this one https://github.com/ngehlert/cobalt2
it is not exactly like the one from @wesbos but it's really close 😄

**Comment by AlmogRnD** [comment]
@ngehlert did not work with the new webstrom version

**Comment by Hongbo-Miao** [comment]
@AlmogRnD same here, move to https://github.com/ngehlert/cobalt2/issues/1

**Comment by ngehlert** [comment]
@AlmogRnD @Hongbo-Miao well i have the newest version 2017.2 :D what version do you use? is there a problem importing the file?

**Comment by Janatbek** [comment]
> Has anyone gotten this to work, I'm getting 404 for github page

https://raw.githubusercontent.com/ngehlert/cobalt2/master/cobalt2.icls

**Comment by ngehlert** [comment]
it's easier to just install the plugin from the jetbrains marketplace in webstorm ;)

pretty soon there will be full IDE support (so not only editor scheme but real UI theme with sidebar and stuff 😉 )
