### ISSUE TITLE
Lists in Markdown

### ISSUE THREAD

**Issue by benjaminrose** [wesbos/cobalt2#87]
Using `cobalt2.tmTheme`, currently lists show up with the same dark back ground that headers do. I was going to change this, at least for myself, but I can't find it in the code. Can anyone help me find where to change this or explain to my why I should keep it this way?

Thanks

**Comment by wesbos** [comment]
Yeah this would be nice to change out - I write a lot of markdown as well. 

I think the scope you'll need to target is `markup.list.unnumbered.markdown`

**Comment by benjaminrose** [comment]
Where are these files located on my disk? I would like to try and change things, but I can't find the file location of where the changed files need to be. I am sure the answer is somewhere on the web, but I have not found it yet. So now I am asking here.

**Comment by wesbos** [comment]
You will have to uninstall your current one, and fork the theme into your packages folder. That will give you access to everything. 

LMK if you need any help.

**Comment by wesbos** [comment]
Okay I've significantly improved this. Enjoy! 

![](https://pbs.twimg.com/media/CaZh3VLUYAAA1-K.png)
