### ISSUE TITLE
Gulpfile.js Toggle Comment Not Working Due To a Theme Issue

### ISSUE THREAD

**Issue by ahmadawais** [wesbos/cobalt2#90]
I am unable to use `SUPER + /` to `toggle_comment` in sublime. I found out that it's a theme issue.
Can you look into this 
https://github.com/jesseweed/seti-ui/issues/202
and 
https://github.com/YabataDesign/afterglow-theme/pull/95/files

**Comment by wesbos** [comment]
I'm not sure why this is a theme issue. Want to submit a PR?

**Comment by ahmadawais** [comment]
@wesbos Can you read the above links. Since I never built a sublime theme they make lesser sense. If you could drop some pointers, I'd love to submit a PR again.
