### ISSUE TITLE
Cobalt2 doesn't show up in Package Manager

### ISSUE THREAD

**Issue by jdhines** [wesbos/cobalt2#93]
Not sure if this is a cobalt issue or a Package Manager issue, or a configuration issue on my end, but I recently noticed I had no file icons, so was going to try to reinstall Cobalt2, only it's not in the package manager.
![image](https://cloud.githubusercontent.com/assets/2855641/12763001/165523a0-c9c0-11e5-8f7b-33737dc44f67.png)

The window and code colors generally seem to be right, so it is using the theme already to a degree (not sure why there's no icons for files, but that's another issue, maybe).

**Comment by jdhines** [comment]
Icon issue solved with https://github.com/wesbos/cobalt2/issues/29

**Comment by wesbos** [comment]
Do you already have it installed? Look under `list packaged`

**Comment by jdhines** [comment]
Yes, it's listed under Theme - Cobalt2. Have I just missed that this is Sublime feature, that the packages you can see in the repo exclude ones you already have? That makes me feel silly.

**Comment by wesbos** [comment]
Yep - its kind of weird. Ideally it would just grey out installed packages, but it just doesn't show them at all.
