### ISSUE TITLE
Problem with tabs

### ISSUE THREAD

**Issue by oilvier** [wesbos/cobalt2#94]
Hi,

Since the last update, I have a problem with the tab system. 
I can barely see the active tab and there's no separation between tabs anymore...

![screenshot_3](https://cloud.githubusercontent.com/assets/1795640/12842053/8a09648c-cbf0-11e5-8933-0c94afc1c340.png)

I use Sublime Text 2 on Windows 10.

Is it just me ?

**Comment by megamoose7** [comment]
I'm experiencing the same problem. My tabs look the same as in your screenshot above and tabs aren't recognizing mouse clicks.

Sublime Text 2 on Windows 7

**Comment by wesbos** [comment]
Looks like a commit for transient tabs isn't jiving. I'll revert it and send an update. Thanks for letting me know!

**Comment by markroland** [comment]
I'm having a similar issue. Can't close tabs that are "single-clicked" to preview. Double-clicked to open tabs are okay.

**Comment by oilvier** [comment]
@wesbos In the meantime, is there a way to revert back to previous version ?

**Comment by wesbos** [comment]
Thanks everyone - I just reverted the commit that introduced this. Run an update on Package Control and restart to get the changes. 

https://github.com/wesbos/cobalt2/releases/tag/2.0.5

**Comment by markroland** [comment]
Thanks, that worked for me. Thanks for the theme!

**Comment by oilvier** [comment]
It's all back to normal. Thanks !

Keep up the good work :+1:

**Comment by caesarsol** [comment]
Hello @oilvier, I made the "Transient tabs" PR, #82 

Can I ask your help in finding the problem? I don't understand if the behavior you experienced is the expected one in the original code - in which case I made a wrong assumption.

The screenshots in the original PR are different from what you had?

thanks!

**Comment by oilvier** [comment]
Hi,
I posted a screenshot of what I had in my first comment. 

The problem compared to the screenshot in the PR is that every tab is transient, even the active one. And the yellow border at the bottom is barely noticeable.

I'm on Windows with Sublime Text 2.

**Comment by caesarsol** [comment]
Hey @oilvier, thanks for the feedback!

Is there anyone that would try ST3 on Windows, to understand if the problem is caused by the Windows binaries or the fact that I'm testing on ST3?

thanks!
