### ISSUE TITLE
Font and Tab missed on update

### ISSUE THREAD

**Issue by haroldSanchezb** [wesbos/cobalt2#95]
Today Cobalt2 updated, but when after restart my sublime, I see this issues, what is wrong? greetings! 

![screenshot at 2016-02-08 09-23-08](https://cloud.githubusercontent.com/assets/355510/12885553/9fa482d4-ce45-11e5-9245-d77fe48bede9.png)
![screenshot at 2016-02-08 09-23-00](https://cloud.githubusercontent.com/assets/355510/12885554/9fa6e448-ce45-11e5-9505-5869ac9f78b1.png)

**Comment by wesbos** [comment]
Looks like Sublime turned off your settings - make sure you have the theme set in your settings file. 

Instructions here:

https://github.com/wesbos/cobalt2#installation
