### ISSUE TITLE
SCSS Syntax highlighting compound selectors

### ISSUE THREAD

**Issue by sdempsey** [wesbos/cobalt2#96]
File this as a question I guess.  I love the theme for 99% of things I do.  I wonder if there is a way to correctly highlight compound selectors in sass, specifically in the scss syntax (and maybe this is an issue to raise with the authors of the syntax plugin - not sure).  

What I like to do (sort of a BEM esque approach.  I have a selector `.custom-tooltip`  I like to create selectors for inner elements such as `.custom-tooltip-content` or `.custom-tooltip-legend`

```scss
.custom-tooltip {
    
    &-content {
        //.custom-tooltip-content styles
    }

    &-legend {
        //.custom-tooltip-legend styles
    }
}
```

Cobal2 renders them like so: 
![screen shot 2016-02-09 at 11 52 30 am](https://cloud.githubusercontent.com/assets/5795146/12923425/b4fcc43c-cf23-11e5-94ea-676b24d92b79.png)

Is there anything I can do within cobalt2 to correct this or should i be bugging the author of the syntax package? 

Thanks,
Sean

**Comment by wesbos** [comment]
Oh wow - I didn't even know this was possible in Sass. 

Do other themes throw this? It's most likely a problem with the scss highlighter as the theme doesn't defined the scope - it just highlights things that scss tells us are errors.

**Comment by wesbos** [comment]
We can fix it, but if it happens in other themes I'd like to have it fixed at the source rather than just painting over it as we have done with other sass stuff

**Comment by sdempsey** [comment]
Other themes cause the same issue - should have looked into that before opening this issue.  
interestingly enough switching the syntax from scss to sass (https://github.com/nathos/sass-textmate-bundle) produces better, though not perfect results.

![screen shot 2016-02-09 at 2 45 11 pm](https://cloud.githubusercontent.com/assets/5795146/12928510/d00e1cae-cf3b-11e5-9b24-4dc12dc9857a.png)

I can go report the issue to the scss syntax repo https://github.com/MarioRicalde/SCSS.tmbundle though I'm not feeling super confident about the commit history (nothing in the last year).

**Comment by wesbos** [comment]
Yeah you'll run into other issues using the sass bundle because that is for .sass files, not .scss files - its a different syntax than what you are using

**Comment by sdempsey** [comment]
Alright, fingers crossed.  Thanks again for the help!

**Comment by wesbos** [comment]
NP - gonna close this but feel free to keep it updated with your findings.
